from tkinter import *

window = Tk()
window.geometry('450x450')
window.title('A picture Story')

def func2a():
  canvas1.pack_forget()
  label1.pack_forget()
  button1a.pack_forget()
  button1b.pack_forget()
  canvas3.pack()
  label3.pack()
  button3a.pack()
  button3b.pack()

def func2b():
  canvas1.pack_forget()
  label1.pack_forget()
  button1a.pack_forget()
  button1b.pack_forget()
  canvas4.pack()
  label4.pack()
  button4a.pack()
  button4b.pack()

def func3a():
  canvas3.pack_forget()
  label3.pack_forget()
  button3a.pack_forget()
  button3b.pack_forget()
  canvas5.pack()
  label5.pack()
  button5a.pack()

def func3b():
  canvas3.pack_forget()
  label3.pack_forget()
  button3a.pack_forget()
  button3b.pack_forget()
  canvas6.pack()
  label6.pack()
  button6a.pack()
  

def func4a():
  canvas4.pack_forget()
  label4.pack_forget()
  button4a.pack_forget()
  button4b.pack_forget()
  canvas7.pack()
  label7.pack()
  button7a.pack()
  
def func4b():
  canvas4.pack_forget()
  label4.pack_forget()
  button4a.pack_forget()
  button4b.pack_forget()
  canvas8.pack()
  label8.pack()
  button8a.pack()

def menu():
  canvas5.pack_forget()
  label5.pack_forget()
  button5a.pack_forget()
  canvas6.pack_forget()
  label6.pack_forget()
  button6a.pack_forget()
  canvas7.pack_forget()
  label7.pack_forget()
  button7a.pack_forget()
  canvas8.pack_forget()
  label8.pack_forget()
  button8a.pack_forget()
  canvas1.pack()
  label1.pack()
  button1a.pack()
  button1b.pack()
  
canvas1 = Canvas(window)
canvas1.pack()
photo1 = PhotoImage(file='mo.png')
photo1 = photo1.subsample(5)
canvas1.create_image(180, 100, image=photo1)
label1 = Label(window, text='This is a story of a man named Jonny', height=2, width=30)
label1.pack()
button1a = Button(window, text='Click here to know more about his education', command=func2a)
button1a.pack()
button1b = Button(window, text='Or you might want to check up his marital life?', command=func2b)
button1b.pack()

canvas2 = Canvas(window)
photo2 = PhotoImage(file='katie.png')
photo2 = photo2.subsample(5)
canvas2.create_image(180, 100, image=photo2)
label2 = Label(window, text='This is a picture of his wife Anita.', height=2, width=40)
button2a = Button(window, text='Wanna know what happened to the marriage?')
button2b = Button(window, text='Some bad things Later happened to Jonny😢')

canvas3 = Canvas(window)
photo3 = PhotoImage(file='3jn2.png')
photo3 = photo3.subsample(3)
canvas3.create_image(180, 100, image=photo3)
label3 = Label(window, text='Jonny was a student of Oxford University in his early years', height=2, width=50)
button3a = Button(window, text="Find out what happened after Johny's University.", command=func3a)
button3b = Button(window, text="The saddest part of Johny's life", command=func3b)

canvas4 = Canvas(window)
photo4 = PhotoImage(file='katie.png')
photo4 = photo4.subsample(3)
canvas4.create_image(180, 100, image=photo4)
label4 = Label(window, text="This is Mrs. Anita, Johny's wife", height=2, width=50)
button4a = Button(window, text="Johny Later regreted marrying this woman! check it out", command=func4a)
button4b = Button(window, text="How can a human being turn to an animal? No! not Johny", command=func4b)

canvas5 = Canvas(window)
photo5 = PhotoImage(file='34.png')
photo5 = photo5.subsample(7)
canvas5.create_image(180, 100, image=photo5)
label5 = Label(window, text="Johny later got married and lived happily ever after with his wife.", height=2, width=50)
button5a = Button(window, text="Return to main menu", command=menu)

canvas6 = Canvas(window)
photo6 = PhotoImage(file='dead.png')
photo6 = photo6.subsample(5)
canvas6.create_image(180, 100, image=photo6)
label6 = Label(window, text="Johny was poisoned to death by the wife he married. Too bad!!", height=2, width=50)
button6a = Button(window, text="Return to main menu", command=menu)

canvas7 = Canvas(window)
photo7 = PhotoImage(file='car.png')
photo7 = photo7.subsample(5)
canvas7.create_image(180, 100, image=photo7)
label7 = Label(window, text="His wife set his car ablaze on a Sunday morning.", height=2, width=50)
button7a = Button(window, text="Return to main menu", command=menu)

canvas8 = Canvas(window)
photo8 = PhotoImage(file='1.png')
photo8 = photo8.subsample(5)
canvas8.create_image(180, 100, image=photo8)
label8 = Label(window, text="And Johny later turned into a bird. it was unbelievable ", height=2, width=50)
button8a = Button(window, text="Return to main menu", command=menu)

window.mainloop()